# 10 jobs
wandb:
  group: sgd+adafactor
optimizer:
  weight_decay: 0.0
  eps: 1.0e-15
  beta_0: 0.9
  beta_1: 0.95
save_num_unsharded_checkpoints_to_keep: 1

sweep:
  - optimizer: 
      name: adafactorw_last
      learning_rate: [0.1, 0.316, 1.0, 3.16, 10, 31.6, 100, 316, 1000, 3160]
      update_last: True
      update_norm: True
      lr_last: 3.16e-3
